### ISSUE TITLE
[bug]: DeprecationWarning for `warning_filter`

### ISSUE THREAD

**Issue by ccoenen** [DariuszPorowski/mkdocs-file-filter-plugin#99]
### 🐛 What happened?

When I build my project, I get these log lines:

```
INFO    -  DeprecationWarning: warning_filter doesn't do anything since MkDocs 1.2
and will be removed soon. All messages on the `mkdocs` logger get counted
automatically.
```

they originate from `mkdocs_file_filter_plugin/logger.py`

### 🔬 How to reproduce?

1. have a mkdocs 1.2+ project (1.5.1 in my case)
2. configure it to use file-filter
3. run `mkdocs serve`

### 🏗️ Code Sample / Log

```Shell
INFO    -  DeprecationWarning: warning_filter doesn't do anything since MkDocs 1.2 and will be removed soon. All messages on the `mkdocs` logger get counted automatically.
```

### 🌌 Environment (plugin version)

0.1.0

### 🌌 Environment (OS)

Linux

### 🌌 Environment (Python)

3.10.12

### 🌌 Environment (MkDocs)

1.5.1

### 📈 Expected behavior

I would expect this not throwing any warnings.

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
@ccoenen thanks for this issue, will try to fix it this week :)
